In [3]:
import numpy as np

In [4]:
a = np.array([10,20,30,40,50,60])
print(a[3])
print(a[1:4])

40
[20 30 40]


In [11]:
#using step
print(a[0:6:2])

[10 30 50]


In [13]:
#negative slicing
print(a[-4:-1])

[30 40 50]


In [24]:
b = np.array([[1,2,3],
               [4,5,6],
                [7,8,8]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 8]]


In [25]:
#slice specific rows
print(b[0:2, :])

[[1 2 3]
 [4 5 6]]


In [26]:
#slice specific columns
print(b[:,1:3])

[[2 3]
 [5 6]
 [8 8]]


In [27]:
#slice sub-matrix
print(b[0:2,1:3])

[[2 3]
 [5 6]]


In [28]:
# step based slicing
print(b[::2,::2])

[[1 3]
 [7 8]]


In [29]:
c = np.array([
             [[1,2], [3,4]],
             [[5,6], [7,8]]
])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# slice first layer
print(c[0,:,:])

[[1 2]
 [3 4]]


In [31]:
print(c[1,0:2,0:1])

[[5]
 [7]]


In [32]:
# slice specific element
print(c[1,0,1])

6
