In [1]:
import numpy as np

Array creation functions

In [2]:
a = np.array([10,20,30,40])
print(np.std(a))

11.180339887498949


In [6]:
print(np.arange(1,20,2))
print(np.arange(6))

[ 1  3  5  7  9 11 13 15 17 19]
[0 1 2 3 4 5]


In [7]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [12]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
a = np.array([1,2,3])
print(np.diag(a))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
