In [1]:
import numpy as np

Functions:

In [21]:
a = np.array([[1,2,3], [4,5,6]])
print(a.shape)  # size of each dimention

(2, 3)


In [22]:
print(a.ndim)  # no of dimentions

2


In [4]:
print(a.size)  # total count of elements across all dimentions

6


In [6]:
print(a.dtype)  # which type of data stored

int64


In [7]:
b = np.array([1,2,3,4,5,6])
print(b.reshape(2,3))  # change the shape of array

[[1 2 3]
 [4 5 6]]


In [9]:
print(a.flatten())   # multidimentional array into single

[1 2 3 4 5 6]


Mathematical functions

In [15]:
print(a.sum())
print(np.sum([1,2,3]))

21
6


In [16]:
print(a.mean())
print(np.mean([10,20,30]))

3.5
20.0


In [20]:
print(np.sort([4,1,3,2]))
c = np.array([6,2,1,9,3])
print(np.sort(c))


[1 2 3 4]
[1 2 3 6 9]


In [24]:
# transpose()
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [27]:
a = np.array([10,40,20,60])
print(a.argmax())    # it returns index
print(a.argmin())

3
0


In [28]:
# axis based operation
b = np.array([[1,2,3], [4,5,6]])
print(b.sum(axis = 0))  # column wise
print(b.sum(axis = 1))  # row wise

[5 7 9]
[ 6 15]


In [29]:
c = np.array([1,2,2,3,4,4])
print(np.unique(c))

[1 2 3 4]


In [30]:
d = np.array([10,30,50,70])
print(np.where(d>40, "High", "Low"))

['Low' 'Low' 'High' 'High']


In [32]:
# clip() - defined minimum and max boundary
e = np.array([10,50,100])
print(np.clip(e,20,80))

[20 50 80]


In [35]:
f = np.array([1.2,2.7,3.5])
print(np.round(f))  # nearest int

[1. 3. 4.]


In [36]:
print(np.floor(f))  # downwards to the nearest int

[1. 2. 3.]


In [37]:
print(np.ceil(f))   # upward to the nearest int

[2. 3. 4.]
