In [1]:
import numpy as np

Joining numpy array

In [2]:
# joining two arrays using concatenate()
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [9]:
# joining two 2-D arrays along rows(axis = 1) using concatenate()  - row wise
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1,arr2), axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2))
print(arr)      

[[1 2 3]
 [4 5 6]]


In [15]:
print(np.stack((arr1,arr2), axis = 1))  

[[1 4]
 [2 5]
 [3 6]]


In [13]:
# stacking along rows - hstack()
print(np.hstack((arr1,arr2)))

[1 2 3 4 5 6]


In [14]:
# stacking column wise - vstack()
print(np.vstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
