In [1]:
import numpy as np

Shallow copy - view()  

In [4]:
#  changes made to one array will reflect in the other
a = np.array([1,2,3,4])
b = a.view()
b[0] = 100
print(a)

[100   2   3   4]


In [3]:
print(b)

[100   2   3   4]


Deep copy - copy()  - 

In [6]:
# changes made to the copied array do not affect the original array
a = np.array([1,2,3,4])
c = a.copy()
c[0] = 100
print(a)
print(c)

[1 2 3 4]
[100   2   3   4]
