In [1]:
import numpy as np

In [2]:
print(np.random.rand(5))

[0.62566209 0.32711351 0.6952801  0.69141379 0.49222848]


In [3]:
print(np.random.randint(1,10,size = 5))

[9 7 3 7 8]


In [4]:
print(np.random.randn(4))

[-0.15951688 -0.1265609   1.15563599  0.856802  ]


In [5]:
print(np.random.random(3))

[0.44720383 0.35563455 0.20041151]


In [6]:
a= np.array([1,2,3,4])
np.random.shuffle(a)
print(a)

[3 1 2 4]


In [15]:

np.random.seed(20)
print(np.random.randint(1,10,3))


[4 5 7]
