In [1]:
import numpy as np

In [4]:
# 1. create array with 5 dim using vector
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print('Shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array: (1, 1, 1, 1, 4)


In [9]:
# 2. conveert 1-D array with 12 elements into 3-d array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
# 3. Try 1d array with 8 elements to a 2d array with 3 elments in each dimension
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(3,3)
print(newarr)     # it gives error

ValueError: cannot reshape array of size 8 into shape (3,3)

In [11]:

# 4 Returns copy or view ?
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)      # it returns view 

[1 2 3 4 5 6 7 8]


In [12]:
# 5 Unknown dimention : 1d array with 8 elements to 3d array with 2X2 elements
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
# 6 convert the array into  a 1d array  
arr = np.array([[1,2,3],[4,5,6]])
print(arr.reshape(-1))     # also use flatten()

[1 2 3 4 5 6]


In [39]:
# 7 Iterate 1-d array
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [40]:
# 8 Iterate 2-d array
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [41]:
# 9 Iterate on each scalar element of the 2-d array
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [42]:
# 10. Iterating 3-d arrays
arr = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print("x represents the 2-D array:")
    print(x)

x represents the 2-D array:
[[1 2 3]
 [4 5 6]]
x represents the 2-D array:
[[ 7  8  9]
 [10 11 12]]


In [43]:
# 11 iterate down to the scalars:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [44]:
# 12 iterating array using nditer()
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [45]:
# 13. iterating array with different data types
arr = np.array([1,2,3])
for x in np.nditer(arr,flags = ['buffered'],op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [46]:
# 14. iterating with diff step-size
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [47]:
# 15. Enumerate on following 1d array elements
arr= np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
    print(idx)

(0,)
(1,)
(2,)


In [48]:
# 16. Enumerate on following 2d array elements
arr = np.array([[1,2,3,4],[5,6,7,8]])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [49]:
# 17. Join two arrays using concatenate()
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [50]:
# 18. Join two 2-d arrays using concatenate()
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [51]:
# 19. Join array using stack fun
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [52]:
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [53]:
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [54]:
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
