In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,4,5,4])
x = np.where(arr==4)
print(x)

(array([3, 4, 6]),)


In [8]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2==0)
print(x)
y = np.where(arr%2==1)
print(y)

(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


In [10]:
# find the indexes where the value 7 should be inserted
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)  # 7 should be inserted on index 1

1


In [11]:
# find the indexes where the value 7 should be inserted starting from the right side
x = np.searchsorted(arr, 7,side='right')
print(x)

2


In [12]:
# find the indexes where the value 2,4,6 should be inserted in the orginal array
arr = np.array([1,3,5,7])
x = np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


In [13]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [14]:
arr = np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [15]:
# sort a boolean array
arr = np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [16]:
# sort a 2-d array
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
