In [1]:
import numpy as np

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[7]

np.int64(18)

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [7]:
arr[:5]

array([11, 12, 13, 14, 15])

In [8]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[3::2]

array([14, 16, 18, 20])

In [11]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [13]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
arr[0]

array([1, 2, 3, 4, 5])

In [15]:
arr[4]

array([21, 22, 23, 24, 25])

In [16]:
arr[4,3]

np.int64(24)

In [19]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [20]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [22]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [24]:
arr[:,2]  #col

array([ 3,  8, 13, 18, 23, 28])

In [26]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
bool_index = arr%2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [33]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])