In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


array([ 6,  7,  8,  9, 10])

In [4]:
a1 +a2   # array size is same when permoming some operations

array([ 7,  9, 11, 13, 15])

In [6]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [7]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [8]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
a1 // a2

array([0, 0, 0, 0, 0])

In [10]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [20]:
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [12]:
l = [10,20,30,40]
arr = np.array(l)

In [13]:
for i in l:          # this is long process so use array (below)
    print(i+10)

20
30
40
50


In [14]:
arr + 10  # broadcasting

array([[20, 30, 40, 50]])

In [16]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr2 = arr2 + 10
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [37]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
slice = a[:5]
slice  = slice * 10
slice

array([10, 20, 30, 40, 50])

In [39]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
a[4:6] * 10

array([50, 60])

In [41]:
a
#b = a  # deep copy = any changes in b then it reflect in a also
b = a.copy()  # shallow copy = no any changes in a 

In [42]:
b[0] = 99

In [43]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [52]:
A

array([[1, 2],
       [3, 4]])

In [53]:
B

array([[5, 6],
       [7, 8]])

In [54]:
A * B

array([[ 5, 12],
       [21, 32]])

In [55]:
A @ B  # this is actually multiplication

array([[19, 22],
       [43, 50]])

In [57]:
np.dot(A,B)  # this is another method

array([[19, 22],
       [43, 50]])

In [58]:
A

array([[1, 2],
       [3, 4]])

In [59]:
A.T   # transpose

array([[1, 3],
       [2, 4]])

In [60]:
A  # you cannot stack two matrix  so we can create two vectors

array([[1, 2],
       [3, 4]])

In [61]:
B

array([[5, 6],
       [7, 8]])

In [62]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [64]:
np.vstack((a,b))  # vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
np.hstack((a,b))   #horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [68]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
np.hsplit(c,2)  # horizontal split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [72]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [74]:
a = np.vsplit(c,2)
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [75]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
