In [4]:
import numpy as np

In [5]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [11]:
b= np.sum(s,axis = 1)   # 1 for row sum
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [13]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [14]:
for i in b:
    print(i)

45
45
45
45
45
45
45
45
45


In [17]:
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("For rows it is valid")

For rows it is valid


In [18]:
c = np.sum(s,axis = 0)   # 0 for column
for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("For column it is valid")

For column it is valid


In [19]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [21]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [22]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [24]:
# instead of slicing use for loop
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n)

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [27]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [72]:
import numpy as np
# columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78],  # student 1
    [19,92,88],  # student 2
    [17,76,95],  #         3
    [18,65,70],  #         4
    [20,90, 85]  #         5
])

In [73]:
# Get the shape of the matrix.
data.shape

(5, 3)

In [74]:
# Find the avg of the matrix.
np.mean(data[:,0])

np.float64(18.4)

In [75]:
# Extract Math marks of all student
data[:,1]

array([85, 92, 76, 65, 90])

In [76]:
# Find the hiest science marks
np.max(data[:,2])

np.int64(95)

In [77]:
#Get the details of the students who scored more than 90 in math.
data[data[:,1] >90]

array([[19, 92, 88]])

In [78]:
# increase Math marks of all students by 5
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [79]:
# Find how many students are younger than  19
len(data[data[:,0]<19])

3

In [80]:
#Calculate  the avg marks in each sub (column-wise maen)
np.mean(data[:,1:], axis = 0)

array([86.6, 83.2])

In [81]:
# GET data of students who scored at least 80 in both subject.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [82]:
# replace all science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])